server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000  # 10s
        response-timeout: 60s   # 60s
      default-filters:
        - name: Retry
          args:
            retries: 2
            methods: GET
            statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, SERVICE_UNAVAILABLE, INTERNAL_SERVER_ERROR
      routes:
        # Players: acepta /api/players/** (passthrough)
        - id: players-service-api
          uri: ${PLAYERS_URI:http://localhost:8081}
          predicates:
            - Path=/api/players/**
        # Players: acepta /players/** y reescribe a /api/players/**
        - id: players-service-noapi
          uri: ${PLAYERS_URI:http://localhost:8081}
          predicates:
            - Path=/players/**
          filters:
            - RewritePath=/players/(?<segment>.*), /api/players/${segment}
        # Players: acepta /players exacto y lo envía a /api/players
        - id: players-service-root
          uri: ${PLAYERS_URI:http://localhost:8081}
          predicates:
            - Path=/players
          filters:
            - SetPath=/api/players
        # Teams: acepta /api/teams/** (passthrough)
        - id: teams-service-api
          uri: ${TEAMS_URI:http://localhost:8082}
          predicates:
            - Path=/api/teams/**
        # Teams: acepta /teams/** y reescribe a /api/teams/**
        - id: teams-service-noapi
          uri: ${TEAMS_URI:http://localhost:8082}
          predicates:
            - Path=/teams/**
          filters:
            - RewritePath=/teams/(?<segment>.*), /api/teams/${segment}
        # Teams: acepta /teams exacto y lo envía a /api/teams
        - id: teams-service-root
          uri: ${TEAMS_URI:http://localhost:8082}
          predicates:
            - Path=/teams
          filters:
            - SetPath=/api/teams
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

