server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000  # 10s
        response-timeout: 60s   # 60s
      default-filters:
        - name: Retry
          args:
            retries: 2
            methods: GET
            statuses: BAD_GATEWAY, GATEWAY_TIMEOUT, SERVICE_UNAVAILABLE, INTERNAL_SERVER_ERROR
      routes:
        # Clientes: acepta /api/clientes/** (passthrough)
        - id: clientes-service-api
          uri: ${PLAYERS_URI:http://localhost:8081}
          predicates:
            - Path=/api/clientes/**
        # Clientes: acepta /clientes/** y reescribe a /api/clientes/**
        - id: clientes-service-noapi
          uri: ${PLAYERS_URI:http://localhost:8081}
          predicates:
            - Path=/clientes/**
          filters:
            - RewritePath=/clientes/(?<segment>.*), /api/clientes/${segment}
        # Clientes: acepta /clientes exacto y lo envía a /api/clientes
        - id: clientes-service-root
          uri: ${PLAYERS_URI:http://localhost:8081}
          predicates:
            - Path=/clientes
          filters:
            - SetPath=/api/clientes
        # Vehiculos: acepta /api/vehiculos/** (passthrough)
        - id: vehiculos-service-api
          uri: ${TEAMS_URI:http://localhost:8082}
          predicates:
            - Path=/api/vehiculos/**
        # Vehiculos: acepta /vehiculos/** y reescribe a /api/vehiculos/**
        - id: vehiculos-service-noapi
          uri: ${TEAMS_URI:http://localhost:8082}
          predicates:
            - Path=/vehiculos/**
          filters:
            - RewritePath=/vehiculos/(?<segment>.*), /api/vehiculos/${segment}
        # Vehiculos: acepta /vehiculos exacto y lo envía a /api/vehiculos
        - id: vehiculos-service-root
          uri: ${TEAMS_URI:http://localhost:8082}
          predicates:
            - Path=/vehiculos
          filters:
            - SetPath=/api/vehiculos
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

