services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: clubdb
      POSTGRES_USER: clubuser
      POSTGRES_PASSWORD: clubpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U clubuser -d clubdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  teams-service:
    build: ../teams-service
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/clubdb
      SPRING_R2DBC_USERNAME: clubuser
      SPRING_R2DBC_PASSWORD: clubpass
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD","wget","-qO-","http://localhost:8081/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  players-service:
    build: ../players-service
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/clubdb
      SPRING_R2DBC_USERNAME: clubuser
      SPRING_R2DBC_PASSWORD: clubpass
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD","wget","-qO-","http://localhost:8082/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  api-gateway:
    build: ../api-gateway
    environment:
      TEAMS_URI: http://teams-service:8081
      PLAYERS_URI: http://players-service:8082
    depends_on:
      teams-service:
        condition: service_healthy
      players-service:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  pgdata:
